Fix "TypeError: Not a function" in `trafficReplay` k6 test (#12642)
When running the trafficReplay k6 test the following error is observed:
TypeError: Not a function: [object Object]

This PR makes sure that there is no confusion which check function is called.

Signed-off-by: Bilyana Gospodinova <bilyana.gospodinova14@gmail.com>